version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: processify_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=file:./prisma/dev.db
      - JWT_SECRET=processify_erp_super_secret_jwt_key_2026
      - CORS_ORIGIN=*
    volumes:
      - sqlite_data:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: processify_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
    driver: local
